{% set version = "0.0.6" %}

package:
  name: tree-sitter-muttrc
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/t/tree-sitter-muttrc/tree_sitter_muttrc-{{ version }}.tar.gz
  sha256: 067c6c4da39248322656cd814f71664ff33a1a3ce06b8fcc1f6e3214fb74a6ed

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
  host:
    - python
    - setuptools >=42
    - wheel
    - pip
  run:
    - python

test:
  commands:
    - pip check
  imports:
    - tree_sitter_muttrc
  requires:
    - pip
    - python

about:
  home: https://github.com/neomutt/tree-sitter-muttrc
  summary: Muttrc grammar for tree-sitter
  license: MIT
  license_file:  LICENSE

extra:
  recipe-maintainers:
    - danielnachun
