schema_version: 1

context:
  version: "0.1.0"

package:
  name: tree-sitter-muttrc
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/t/tree-sitter-muttrc/tree_sitter_muttrc-${{ version }}.tar.gz
  sha256: 6f90bc70a0f7b0a661c50805e97742a784002cb17ab8a3b3896fb486d54f591e

build:
  number: 0
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - if: build_platform != target_platform
      then:
        - cross-python_${{ target_platform }}
        - python
  host:
    - python
    - setuptools >=42
    - wheel
    - pip
  run:
    - python

tests:
  - python:
      imports:
        - tree_sitter_muttrc
  - requirements:
      run:
        - pip
        - python
    script:
      - pip check

about:
  summary: Muttrc grammar for tree-sitter
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/neomutt/tree-sitter-muttrc

extra:
  recipe-maintainers:
    - danielnachun
